### ISSUE TITLE
[Bug] Buttons overlap with spyglass improvements mod

### ISSUE THREAD

**Issue by Anonyku05** [Estecka/mc-PackRule-Menus#10]
In the title. Look the screenshot below (1.20.4 fabric):
![image](https://github.com/Estecka/mc-PackRule-Menus/assets/48128391/bb470daf-c50e-43f9-8c68-30cd8959e59e)

**Comment by Estecka** [comment]
I may take a closer look at this later, but this looks identical to #9. There's little I can do to avoid buttons ovelaping that I don't already do; the fix most likely needs to come from the spyglass mod.

If you report that issue to them, make sure to give them a link them to #9, as it contains instructions on how to fix this.

**Comment by Anonyku05** [comment]
I made a report to them, thanks for the help.

**Comment by Estecka** [comment]
Just had a quick look at their source and yep, they do what I feared and place their button at fixed coordinates.

I should also provide a link to my own mixin, that will give a concrete example on how to do it cleanly:
https://github.com/Estecka/mc-PackRule-Menus/blob/da2ef99c8f9e07675f15491153a7717f0a4c553c/src/main/java/tk/estecka/packrulemenus/mixin/OptionScreenMixin.java#L46C52-L46C81
